server:
  port: 20003

spring:
  application:
    name: community-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/community-server?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: root

# mybatis 扫描映射关系
mybatis:
  mapper-locations: classpath:mapper/*.xml

# logback 配置
logging:
  config:
    classpath: logback-spring.xml